baseURL = 'https://odhyp.github.io/'
languageCode = 'en-us'
title = 'Odhy'
theme = 'odai-theme'

# Author information
[params]
  author = "Odhy Pradhana"

# Hugo Module version requirement
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

# Git Info for Last Modify Date
enableGitInfo = true

# Markup highlighting configuration
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-dark'
    tabWidth = 4
